// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           32
// Async Callback:                       1
// Total number of exported functions:  34

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    jex_sc_dex_pair
    (
        issueLpToken
        enableMintBurn
        addInitialLiquidity
        configureLiqProvidersFees
        configurePlatformFees
        pause
        unpause
        addLiquidity
        addLiquiditySingle
        removeLiquidity
        removeLiquiditySingle
        swapTokensFixedInput
        swapTokensFixedOutput
        estimateAmountIn
        estimateAmountOut
        estimateAddLiquiditySingle
        estimateRemoveLiquidity
        estimateRemoveLiquiditySingle
        getFirstToken
        getSecondToken
        getStatus
        getAnalyticsForLastEpochs
        getLpFees
        getTradingVolume
        getLiqProvidersFees
        getPlatformFees
        getPlatformFeesReceiver
        getFirstTokenReserve
        getSecondTokenReserve
        getLpToken
        getLpTokenSupply
        isPaused
        callBack
    )
}
